### ISSUE TITLE
Why using TypeEvaluator instead of Interpolator in this library？

### ISSUE THREAD

**Issue by tankcong** [daimajia/AnimationEasingFunctions#6]
[PropertyAnimation](http://developer.android.com/guide/topics/graphics/prop-animation.html#interpolators)文档里似乎更推荐通过自定义Interpolator来控制所选属性的变化率。而TypeEvaluator的描述是：If you want to animate a type that is **_unknown**_ to the Android system, you can create your own evaluator by implementing the TypeEvaluator interface，似乎更加强调针对自定义类型或属性改变的情况。
自己在项目中几乎都使用Interpolator，这里不太明白，请教一下。
Thank you!:)

**Comment by hujiaweibujidao** [comment]
@tankcong 两者本质上是差不多的，欢迎阅读[当数学遇上动画系列](http://hujiaweibujidao.github.io/blog/2016/05/26/when-math-meets-android-animation/)，这里有详细解释 :-)

**Comment by daimajia** [comment]
@tankcong This is a really good question. And it's also the hardest part of this library.

Since easing functions need[ four parameters](https://github.com/daimajia/AnimationEasingFunctions/blob/master/library/src/main/java/com/daimajia/easing/BaseEasingMethod.java#L70-L78)

- time
- begin value
- value change
- duration

If you try to use interpolator, you are unable to get or calculate all the value from Interpolator. 

The following code is calculating these four parameters:
https://github.com/daimajia/AnimationEasingFunctions/blob/master/library/src/main/java/com/daimajia/easing/BaseEasingMethod.java#L70-L78
